### ISSUE TITLE
Windows run of "python corenlp.py" Error

### ISSUE THREAD

**Issue by partizanos** [dasmith/stanford-corenlp-python#36]
Use Windows 7 machine, 
Python 2.7.11
java version "1.7.0_80"
Java(TM) SE Runtime Environment (build 1.7.0_80-b15)
Java HotSpot(TM) 64-Bit Server VM (build 24.80-b11, mixed mode)

Traceback (most recent call last):
  File "corenlp.py", line 257, in <module>
    nlp = StanfordCoreNLP()
  File "corenlp.py", line 163, in **init**
    self.corenlp = pexpect.spawn(start_corenlp)
AttributeError: 'module' object has no attribute 'spawn'

**Comment by rbhood** [comment]
Same issue here :( :(

**Comment by lildutchie99** [comment]
Pexpect relies on some Unix-only function, and even using winpexpect the spawn function won't work. I'm giving up on this wrapper for Windows, just gonna write a server in Java that'll run alongside the Python app.

**Comment by 85405115** [comment]
i have this problem. first i run python in windows. then i thought that perhaps running python in windows has problems and therefore i use python in Linux. but i have this problem again in Linux. please help me. what can i do to solve this problem?

**Comment by gracetambunan** [comment]
anyone have solve the problem?
please share :)

**Comment by arsalanamjid** [comment]
Can i run it on a virtual machine on VMware? I am facing the same problem and need a quick fix!

**Comment by FahmaBakkar** [comment]
For windows users can use the codeline

>  self.corenlp = pexpect.popen_spawn.PopenSpawn(start_corenlp) instead of this 

> self.corenlp = pexpect.spawn(start_corenlp)
