### ISSUE TITLE
could you add windows support?

### ISSUE THREAD

**Issue by BlankRain** [dasmith/stanford-corenlp-python#49]
```
PS F:\gitwork\stanford-corenlp-python> python corenlp.py
Traceback (most recent call last):
  File "corenlp.py", line 257, in <module>
    nlp = StanfordCoreNLP()
  File "corenlp.py", line 163, in __init__
    self.corenlp = pexpect.spawn(start_corenlp)
AttributeError: 'module' object has no attribute 'spawn'
```
https://github.com/pexpect/pexpect/issues/321
http://pexpect.readthedocs.io/en/stable/overview.html#pexpect-on-windows

could you add windows support?

**Comment by StatguyUser** [comment]
+1
