### ISSUE TITLE
I have an error and, if it's something you're aware of, wondered if you can help me with a fix?

### ISSUE THREAD

**Issue by nikhil-shrestha** [dasmith/stanford-corenlp-python#56]
python corenlp.py
Traceback (most recent call last):
  File "corenlp.py", line 257, in <module>
    nlp = StanfordCoreNLP()
  File "corenlp.py", line 163, in __init__
    self.corenlp = pexpect.spawn(start_corenlp)
  File "/usr/local/lib/python2.7/dist-packages/pexpect/pty_spawn.py", line 198, in __init__
    self._spawn(command, args, preexec_fn, dimensions)
  File "/usr/local/lib/python2.7/dist-packages/pexpect/pty_spawn.py", line 271, in _spawn
    'executable: %s.' % self.command)
pexpect.exceptions.ExceptionPexpect: The command was not found or was not executable: java.

**Comment by naveenk903** [comment]
same issue as above
`ExceptionPexpect: The command was not found or was not executable: java`

**Comment by arsalanamjid** [comment]
Install java, that fixed the error for me!

**Comment by nabhanabdulla** [comment]
You should install jdk8
