### ISSUE TITLE
Corenlp.py does not loading any modules

### ISSUE THREAD

**Issue by FahmaBakkar** [dasmith/stanford-corenlp-python#62]
> Traceback (most recent call last):
>   File "D:\fahma\corefernce resolution\stanford-corenlp-python-master\corenlp.py", line 281, in <module>
>     nlp = StanfordCoreNLP()
>   File "D:\fahma\corefernce resolution\stanford-corenlp-python-master\corenlp.py", line 173, in __init__
>     self.corenlp.expect("done.", timeout=20) # Load pos tagger model (~5sec)
>   File "C:\Python27\lib\site-packages\pexpect\spawnbase.py", line 341, in expect
>     timeout, searchwindowsize, async_)
>   File "C:\Python27\lib\site-packages\pexpect\spawnbase.py", line 369, in expect_list
>     return exp.expect_loop(timeout)
>   File "C:\Python27\lib\site-packages\pexpect\expect.py", line 117, in expect_loop
>     return self.eof(e)
>   File "C:\Python27\lib\site-packages\pexpect\expect.py", line 63, in eof
>     raise EOF(msg)
> EOF: End Of File (EOF).
> <pexpect.popen_spawn.PopenSpawn object at 0x021863B0>
> searcher: searcher_re:
>     0: re.compile('done.')

**Comment by danielhhoskins** [comment]
@FahmaBakkar I'm having the exact same problem. Have you found a solution? 

@dasmith Do you have any ideas what the problem is? I've spent a couple hours on this problem and haven't been able to solve it.
