### ISSUE TITLE
jsonrpc import error: ValueError, err :

### ISSUE THREAD

**Issue by rishanfaliq** [dasmith/stanford-corenlp-python#63]
Hello, So iv been trying to use corenlp as a wrapper for Stanfordnlp for coreference resolution. But im having issues with the corenlp.py file. There was one error in the downloaded file which was 

Exception, err:
needs to writted as 
Exception as err:

But when i correct this the jsonrpc import doesnt work as a method within the import is throwing this error.

Traceback (most recent call last):
  File "corenlp.py", line 24, in <module>
    import jsonrpc, pexpect
  File "D:\NLP\NaturalLanguageProcessing\stanford-corenlp-python\jsonrpc.py", line 376
    except ValueError, err:
                     ^
SyntaxError: invalid syntax

Any help would be much appreciated, Thanks in advance. Also would be agreat help if you could suggest any known API's for coreference resolution or a wrapper for stanfordnlp that has coreference resolution

**Comment by theanhle** [comment]
Continue fixing in jsonrpc.py file.

**Comment by amitjslearn** [comment]
> Continue fixing in jsonrpc.py file.

What?

**Comment by amitjslearn** [comment]
> Hello, So iv been trying to use corenlp as a wrapper for Stanfordnlp for coreference resolution. But im having issues with the corenlp.py file. There was one error in the downloaded file which was
> 
> Exception, err:
> needs to writted as
> Exception as err:
> 
> But when i correct this the jsonrpc import doesnt work as a method within the import is throwing this error.
> 
> Traceback (most recent call last):
> File "corenlp.py", line 24, in
> import jsonrpc, pexpect
> File "D:\NLP\NaturalLanguageProcessing\stanford-corenlp-python\jsonrpc.py", line 376
> except ValueError, err:
> ^
> SyntaxError: invalid syntax
> 
> Any help would be much appreciated, Thanks in advance. Also would be agreat help if you could suggest any known API's for coreference resolution or a wrapper for stanfordnlp that has coreference resolution

Did you resolve this error?
